"""Extract the two row-ranged packers from main.c into pack_extracted.inc.

EXTRACTED, NOT COPIED. These functions are static inside a 6,600-line file that
cannot be compiled on a host, and a hand-copied duplicate would drift from the
code the board runs -- at which point the test would be certifying the copy.
Pulling the live text at build time means a change to main.c either shows up in
the test or breaks the extraction loudly.

  python gen_pack_slice_src.py
  gcc -O2 -Wall -o pack_slice_test pack_slice_test.c
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MAIN = os.path.join(HERE, "..", "src", "main.c")
OUT = os.path.join(HERE, "pack_extracted.inc")

WANT = ["pack_input_group_major_generic_rows", "pack_gm_c3_neon_rows"]


def extract(text, name):
    """Return the whole definition of `name`, brace-matched."""
    m = re.search(r"^static void " + re.escape(name) + r"\(", text, re.M)
    if not m:
        raise SystemExit("FAIL: %s not found in main.c" % name)
    i = text.index("{", m.start())
    depth, j = 0, i
    while j < len(text):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                return text[m.start():j + 1]
        j += 1
    raise SystemExit("FAIL: unterminated body for %s" % name)


def main():
    src = open(MAIN, encoding="utf-8", errors="surrogateescape").read()
    parts = [
        "/* GENERATED by gen_pack_slice_src.py -- do not edit.",
        " * Extracted verbatim from src/main.c so the test cannot drift from",
        " * the code the board runs. Regenerate after touching the packers.",
        " */",
        "",
    ]
    for name in WANT:
        body = extract(src, name)
        parts.append("/* ---- %s ---- */" % name)
        parts.append(body.replace("static void ", "static void ", 1))
        parts.append("")
    open(OUT, "w", encoding="utf-8").write("\n".join(parts))
    print("wrote %s (%d bytes, %d functions)"
          % (os.path.basename(OUT), os.path.getsize(OUT), len(WANT)))


if __name__ == "__main__":
    main()
